name: Tombo Windows Build Microsoft Visual Studio

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build Tombo Visual Studio Project
        working-directory: Win32/Tombo
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars32.bat" && msbuild  /p:Platform=Win32 /p:Configuration=Release

      # "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" && msbuild
      # ...

      - name: Upload EXEs
        uses: actions/upload-artifact@v4
        with:
          name: Tombo_x86
          path: |
            ./**/*.exe
            Win32/expat/lib/Win32/libexpatw.dll
            Win32/oniguruma/win32/oniguruma.dll
